# Generated by Django 3.2.6 on 2021-08-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='state',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four')], default=1),
        ),
    ]
