# Generated by Django 3.2.6 on 2021-11-20 04:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_auto_20211118_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.IntegerField(choices=[(1, 'Show Order To Offer'), (2, 'Notify Driver Exp Accept'), (3, 'Return To Offer')])),
                ('time_run', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'TBJobTrigger',
                'verbose_name_plural': 'TBJobTriggers',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='CreateTrigger',
        ),
        migrations.AlterModelOptions(
            name='runtrigger',
            options={'ordering': ['-id'], 'verbose_name': 'TBRunTrigger', 'verbose_name_plural': 'TBRunTriggers'},
        ),
        migrations.RemoveField(
            model_name='runtrigger',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='runtrigger',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='runtrigger',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='jobtrigger',
            name='trigger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='run_trigger', to='weather.runtrigger'),
        ),
    ]
