# Generated by Django 3.2.6 on 2021-11-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0009_auto_20211120_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtrigger',
            name='time_run',
        ),
        migrations.RemoveField(
            model_name='runtrigger',
            name='finished_time',
        ),
        migrations.RemoveField(
            model_name='runtrigger',
            name='started_time',
        ),
        migrations.AddField(
            model_name='jobtrigger',
            name='finished_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runtrigger',
            name='time_run',
            field=models.DateTimeField(default='2020-10-10'),
            preserve_default=False,
        ),
    ]
